name: Build Windows Installer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: |
        cd simple_live_app
        flutter pub get

    - name: Build Windows app
      run: |
        cd simple_live_app
        flutter build windows --release

    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/SILENT" -Wait

    - name: Create Inno Setup script
      run: |
        $innoScript = @"
        [Setup]
        AppName=Simple Live App
        AppVersion=1.9.3
        AppPublisher=Simple Live Team
        AppPublisherURL=https://github.com/sword0922/simple-live-APK
        AppSupportURL=https://github.com/sword0922/simple-live-APK
        AppUpdatesURL=https://github.com/sword0922/simple-live-APK
        DefaultDirName={autopf}\SimpleLiveApp
        DefaultGroupName=Simple Live App
        AllowNoIcons=yes
        OutputDir=.
        OutputBaseFilename=SimpleLiveApp-Setup
        Compression=lzma
        SolidCompression=yes
        WizardStyle=modern
        PrivilegesRequired=admin

        [Languages]
        Name: "chinesesimp"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
        Name: "english"; MessagesFile: "compiler:Default.isl"

        [Tasks]
        Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

        [Files]
        Source: "simple_live_app\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

        [Icons]
        Name: "{group}\Simple Live App"; Filename: "{app}\simple_live_app.exe"
        Name: "{group}\{cm:UninstallProgram,Simple Live App}"; Filename: "{uninstallexe}"
        Name: "{autodesktop}\Simple Live App"; Filename: "{app}\simple_live_app.exe"; Tasks: desktopicon

        [Run]
        Filename: "{app}\simple_live_app.exe"; Description: "{cm:LaunchProgram,Simple Live App}"; Flags: nowait postinstall skipifsilent
        "@
        
        $innoScript | Out-File -FilePath "installer.iss" -Encoding UTF8

    - name: Compile installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: simple-live-app-installer
        path: SimpleLiveApp-Setup.exe
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: SimpleLiveApp-Setup.exe
        name: Simple Live App Windows Installer v${{ github.run_number }}
        tag_name: windows-installer-v${{ github.run_number }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
